//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblImportOrders = new HashSet<tblImportOrder>();
            this.tblOrders = new HashSet<tblOrder>();
            this.tblReviews = new HashSet<tblReview>();
            this.tblSuppliers = new HashSet<tblSupplier>();
        }
    
        public int PK_iAccountID { get; set; }
        public int FK_iPermissionID { get; set; }
        public string sEmail { get; set; }
        [MinLength(6, ErrorMessage = "Mật khẩu phải có ít nhất 6 ký tự.")]
        public string sPass { get; set; }
        public string sUserName { get; set; }
        public string sPhone { get; set; }
        public string sAddress { get; set; }
        public Nullable<int> iState { get; set; }

        [Display(Name = "Tôi đồng ý với các Điều khoản và chính xác của Ngõ Handmade")]
        [Range(typeof(bool), "true", "true", ErrorMessage = "Bạn phải đồng ý với các Điều khoản và Điều kiện để đăng ký.")]
        public bool TermsAccepted { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImportOrder> tblImportOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual tblPermission tblPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReview> tblReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplier> tblSuppliers { get; set; }
    }
}
